### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by johnf** [zilkey/active_hash#100]
Here is some code for adding validations in case someone else needs it. Heavily borrowed from ActiveRecord

``` ruby
 module ActiveHash
  class RecordInvalid < StandardError
    attr_reader :record

    def initialize(record)
      @record = record
      errors = @record.errors.full_messages.join(", ")
      super("Validation failed: #{errors}")
    end
  end

  module Validations
    extend ActiveSupport::Concern
    include ActiveModel::Validations

    def save(options={})
      perform_validations(options) ? super : false
    end

    def save!(options={})
      perform_validations(options) ? super : raise_record_invalid
    end

    def valid?(context = nil)
      context ||= (new_record? ? :create : :update)
      output = super(context)
      errors.empty? && output
    end

    alias_method :validate, :valid?
    def validate!(context = nil)
      valid?(context) || raise_record_invalid
    end

    protected

    def raise_record_invalid
      raise(RecordInvalid.new(self))
    end

    def perform_validations(options={}) # :nodoc:
      options[:validate] == false || valid?(options[:context])
    end
  end
end
```

**Comment by kbrock** [comment]
Where is the best place for this?

- README (this is getting quite long. not sure the best way to split this up)
- Module (do we want to support)
- Examples (not sure where this would go)

Another great example would be how to leverage active model.

**Comment by johnf** [comment]
I'd be pretty keen to do a pull request to turn this into a module that can then be included
for example you would do

``` ruby
class Host < ActiveHash::Base  
  include ActiveHash::Validations
  # ...
end
```

**Comment by johnf** [comment]
Two things here I suppose.

This model used to be in the database so I had existing validations and it felt like it would make sense to keep them. This could be arbitrary though.
 
The second was a problem I had with factory girl. I had added the model to factory girl, which seemed to make sense but maybe in hindsight it doesn't?

Anyway I hit a weird bug where strange things were happening. It ended up that factory girl was creating duplicate entries.

So I wanted a uniqueness validator to let me know this was going on.

**Comment by zilkey** [comment]
I've seen a lot of problems adding ActiveHash objects at runtime (like with FactoryGirl).  Unless you are really careful, and completely reload the data after every test run, you get pollution.

If that's the main drive, I'm less likely to want to pull it in.  I could see a scenario where maybe you are hand-editing large files, and maybe have duplicate ids or names by mistake, but that seems like more of a one-off development-time check.  I'm tempted to say just make a quick gem for this and release it separately.  Thoughts?

**Comment by flavorjones** [comment]
I agree that this would make sense as a separate gem.

**Comment by stefanjohncollier** [comment]
Hi all,
Did this get turned into a gem in the end?
We'd be keen to use these.
