### ISSUE TITLE
Pass Default Field Values to @attributes

### ISSUE THREAD

**Issue by brunchgroupe** [zilkey/active_hash#107]
Not sure if this is by design, but currently the default values are passed to each field, but not the attributes hash when creating a new record. Mine might be an edge case but what I'm looking for is something like:

```ruby
class Ticket < ActiveHash::Base
  field :quantity
  field :type, :default => "General Admission" 
  field :purchase_id, :default => "1189898495947654440"
end

payload = Ticket.new(:quantity => 4).attributes
# => {:quantity => 4, :type => "General Admission", :purchase_id => "1189898495947654440"}

```
**Background:** I'm building stub server which will be used for testing several services with shared dependencies; dynamic stub creation is necessary(easier) in test cases with complex stub manipulation.

**Comment by flavorjones** [comment]
Agree, this is what I'd expect from `#attributes`
