### ISSUE TITLE
`where` method should use default values in selections

### ISSUE THREAD

**Issue by zimkies** [zilkey/active_hash#110]
assuming I have a City object:

```
 class City < ActiveYaml::Base
    field :active, default: true

    def self.active
        where(active: true)
    end
end
```

In the above statement, `City.active` should return all cities unless they explicitly list `active: false`. Currently this does not do this, which is very misleading and could lead to many bugs

**Comment by kbrock** [comment]
This seems tricky

What do you think about a method that will go through the data and change any nil values to the corresponding default value?

That seems doable and wouldn't take a performance hit for everyone.

Or maybe the load yaml method could be changed to take defaults into account

**Comment by kbrock** [comment]
@zimkies The defaults sets the values for new records.

Are you expecting ActiveHash to modify the values that come out of the yaml file?
What do you think about ActiveHash modifying the records as they are read out of the yaml file? Or maybe a post processing step to set them.

**Comment by kbrock** [comment]
see also #97
