### ISSUE TITLE
No joins/includes option?

### ISSUE THREAD

**Issue by llermaly** [zilkey/active_hash#112]
Hello,  I'm using active_hash to manage communes/regions , then when I try to use joins statement throws this error :  

School.includes(:commune) 
NoMethodError: undefined method `type_for_attribute'  for Model.class

School.joins(:commune)
NoMethodError: undefined method `table_name' for  Model.class

Thanks

**Comment by kbrock** [comment]
@llermaly Errors like that look like either not using ActiveModel, or not properly including all the necessary interfaces

ActiveRecord tends to use those methods when using relations.

1. Are both `School` and `Commune`  active hash objects?
2. If you define those methods, does it get one step closer?
3. Have you looked into ActiveModel to see if there is something that will help here?

**Comment by llermaly** [comment]
@kbrock Thanks for your amazing fast answer,  

School is an ActiveRecord object , 

This is how my Comune model looks 

class Commune < ActiveHash::Base
    include ActiveHash::Associations
    belongs_to :region    
    has_many :schools
end

And School 

class School < ActiveRecord::Base
    resourcify 
    has_many :grades, :dependent => :delete_all
    has_many :orders, :dependent => :delete_all
    attr_accessor :region
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :commune
end

All operations like School.last.commune.name , School.last.comune.region.name, works perfectly

Im new with Activehash , I hope I can make joins

regards!

**Comment by kbrock** [comment]
This looks like `ActiveRecordExtensions` should fix. Maybe mix into `commune`?

You may get some hints from [spec](https://github.com/zilkey/active_hash/blob/master/spec/associations/active_record_extensions_spec.rb)

**Comment by llermaly** [comment]
could you be more specific please??  I appreciate your help a lot , I dont want to store communes on DB

**Comment by kbrock** [comment]
Hmm, ignore my last thought. it looks like you did it right.

May I ask why you are using `includes`?
I tend to use that to reduce sql queries. Since this is already in memory, not sure what you would gain.

Are you hoping that the model would ignore the `includes(:comune)`?

**Comment by llermaly** [comment]
yeah sounds weird , but I'm using a datatables-gem that requires a joins/includes to be able to use sorting/searching functions

**Comment by kbrock** [comment]
yea, I had a feeling you had a gem that was being smart.

Those values won't be in the database, so you'd need a case statement or something to generate those values server side (if you want to sort on it)

If it is a filter, then you'd basically need to search commune to derive commune id:

```ruby
School.where(:commune_id => Commune.select {|x| x.name =~ 'good'}.map.id)
```

If it is a sort, then you'd need to map the column to a case statement

```ruby
class Commune
  def name_id_case(column = "commune_id")
  "case #{column} " +
    all.map { |id, c| "when #{id} then '#{c.name}' " } +
  "else null end"
end

School.select("school.*, {#{Commune.name_id_case}} AS commune_name").order("commune_name")
```

Note, that is browser only code. but hope it is close.
If you are using an external gem, not sure how you'd plug it in.

**Comment by kbrock** [comment]
@llermaly how did you fare with this?

**Comment by syguer** [comment]
I'll close this. If you need this again, please reopen.
Thanks.
