### ISSUE TITLE
How to set active hash yml with different environment

### ISSUE THREAD

**Issue by ShiningBomb** [zilkey/active_hash#154]
I would something like

if(environment=production)
- id: 1
  code: AAA
  currency: usd
  deposit: true
  withdraw: true
- id: 2
  code: AAB
  currency: usd
  deposit: true
  withdraw: true
else
- id: 1
  code: QQQ
  currency: usd
  deposit: true
  withdraw: true
- id: 2
  code: QQR
  currency: usd
  deposit: true
  withdraw: true
end

How to manage them in one yml?

**Comment by syguer** [comment]
Maybe impossible 🤔 
YAML doesn't have control structure. So you should separate file by each environment, and change loading file depending on environment ( using `set_root_path` and/or `set_filename`.
