### ISSUE TITLE
.where("id>?", 0) not working

### ISSUE THREAD

**Issue by joshm1204** [zilkey/active_hash#176]
Does active hash have the ability to search by >, < operators? If not, what is the preferred solution?

**Comment by syguer** [comment]
It doesn't. Simple solution we known is to use `Enumerable#select`

**Comment by okuramasafumi** [comment]
@joshm1204 Hi, ActiveHash `where` method now takes range argument so you can do something like `foo.where(id: 0..Float::Infinity)`
