### ISSUE TITLE
Why is version 2.2 dependent on Ruby 2.4 and Rails 5?

### ISSUE THREAD

**Issue by hunterae** [zilkey/active_hash#180]

**Comment by okuramasafumi** [comment]
Ruby 2.4 has not reached EOL, so it should be supported IMO.

**Comment by hunterae** [comment]
@okuramasafumi , I don't have a problem with supporting Ruby 2.4. My issue is that this gem requires Ruby 2.4 or greater and Rails 5 or greater, and I'm not convinced the latest changes require those restrictions.

**Comment by syguer** [comment]
Hi @hunterae .
I pick up some our philosophy.

1. We don't support all ActiveRecord versions by one code
1. We decide to change stable version for supporting several ActiveRecord versions
1. We don't want to support Ruby and Rails reached EOL

As a result, our gem restrict Ruby and Rails version like now.
If you want to use new feature on old version, apply monkey patch, or PR is welcome if it works correctly.

**Comment by hunterae** [comment]
@syguer , while I can appreciate trying to encourage using the latest and greatest, is there really anything in the codebase that wouldn't be supported by say Ruby 2.0 or Rails 4? Why not just setup the testing Matrix for Travis CI to ensure that the whole test suite passes on different versions of Ruby and Rails 4. 

I believe most companies have probably made the leap to Rails 4, there are some (the one I work for included) that are slowly working our way up to 5.
